_format_version: "3.0"
services:
- host: details.bookinfo.svc.cluster.local
  id: 88316893-4168-5e2b-8196-3ea6879b23f4
  name: bookinfo-api_details-id
  path: /
  plugins: []
  port: 9080
  protocol: http
  routes:
  - id: bf5d614e-23ef-5f41-ad82-0c24d8086caf
    methods:
    - GET
    name: bookinfo-api_getproductdetails
    path_handling: v1
    paths:
    - ~/details/(?<id>[^#?/]+)$
    plugins: []
    preserve_host: false
    regex_priority: 99
    strip_path: false
    tags: []
  tags: []
- host: productpage.bookinfo.svc.cluster.local
  id: 5ad77fc4-6365-5596-92e2-0d31b807f483
  name: bookinfo-api_products
  path: /api/v1
  plugins: []
  port: 9080
  protocol: http
  routes:
  - id: bf9bfd83-a45f-541a-8aee-4fba43e50c38
    methods:
    - GET
    name: bookinfo-api_getproducts
    path_handling: v1
    paths:
    - ~/products$
    plugins: []
    preserve_host: false
    regex_priority: 200
    strip_path: false
    tags: []
  tags: []
- host: productpage.bookinfo.svc.cluster.local
  id: 25429dbc-1c5f-5482-a786-db3031499444
  name: bookinfo-api_products-id
  path: /api/v1
  plugins: []
  port: 9080
  protocol: http
  routes:
  - id: 5d7038a3-d5e2-5dbc-96de-b2cfbd8786a5
    methods:
    - GET
    name: bookinfo-api_getproduct
    path_handling: v1
    paths:
    - ~/products/(?<id>[^#?/]+)$
    plugins: []
    preserve_host: false
    regex_priority: 199
    strip_path: false
    tags: []
  tags: []
- host: ratings.bookinfo.svc.cluster.local
  id: 5d907df6-7a29-556e-b4e2-c6c3edb0c12f
  name: bookinfo-api_products-id-ratings
  path: /api/v1
  plugins: []
  port: 9080
  protocol: http
  routes:
  - id: 231f1e67-8ea8-58a5-b68a-bc94556f9e65
    methods:
    - GET
    name: bookinfo-api_getproductratings
    path_handling: v1
    paths:
    - ~/products/(?<id>[^#?/]+)/ratings$
    plugins: []
    preserve_host: false
    regex_priority: 99
    strip_path: false
    tags: []
  tags: []
- host: reviews.bookinfo.svc.cluster.local
  id: e55a8645-22d9-50c2-8243-e671905f3b6d
  name: bookinfo-api_products-id-reviews
  path: /api/v1
  plugins: []
  port: 9080
  protocol: http
  routes:
  - id: 0af1888b-4ef0-52c3-96db-3bc5f391df58
    methods:
    - GET
    name: bookinfo-api_getproductreviews
    path_handling: v1
    paths:
    - ~/products/(?<id>[^#?/]+)/reviews$
    plugins: []
    preserve_host: false
    regex_priority: 99
    strip_path: false
    tags: []
  tags: []
upstreams: []
