_format_version: "3.0"
_konnect:
  control_plane_name: kong-work
plugins:
- config:
    ai_metrics: false
    bandwidth_metrics: true
    latency_metrics: true
    per_consumer: false
    status_code_metrics: true
    upstream_health_metrics: true
    wasm_metrics: false
  enabled: true
  name: prometheus
  protocols:
  - grpc
  - grpcs
  - http
  - https
services:
- connect_timeout: 60000
  enabled: true
  host: api.kong-air.com
  name: Kong-Air-Flights-API-20251107062626564
  path: /flights
  port: 443
  protocol: https
  read_timeout: 60000
  retries: 5
  routes:
  - https_redirect_status_code: 426
    id: 9a5dd255-c746-495b-b5b8-c460206f3db3
    path_handling: v0
    paths:
    - /flights
    preserve_host: false
    protocols:
    - http
    - https
    regex_priority: 0
    request_buffering: true
    response_buffering: true
    strip_path: true
  write_timeout: 60000
