add-plugins:
  - selectors:
      - $..services[*]
    overwrite: false
    plugins:
      - name: rate-limiting-advanced
        config:
          limit:
            - 20
          window_size:
            - 30
          hide_client_headers: false
          namespace: service_plugins
      - name: key-auth
        config:
          key_names:
            - apikey
          hide_credentials: false
