apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: kong-pool
  namespace: metallb-system
spec:
  addresses:
    - 172.21.255.200-172.21.255.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: kong-l2
  namespace: metallb-system
spec:
  ipAddressPools:
    - kong-pool
